# This file is auto-generated by the dh-umc tools and should not be edited!
msgid ""
msgstr ""
"Project-Id-Version: univention-management-console-module-quota\n"
"Report-Msgid-Bugs-To: packages@univention.de\n"
"POT-Creation-Date: 2011-11-25 19:42+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: umc/python/quota/tools.py:70
#, python-format
msgid "%s Days"
msgstr "%s Tage"

#: umc/python/quota/partition.py:57 umc/python/quota/partition.py:89
#: umc/python/quota/user.py:57
#, python-format
msgid "Could not open %s"
msgstr "Konnte %s nicht öffnen"

#: umc/python/quota/tools.py:135
msgid "Device could not be found"
msgstr "Partition konnte nicht gefunden werden"

#: umc/python/quota/tools.py:68
msgid "Expired"
msgstr "Abgelaufen"

#: umc/python/quota/user.py:139
#, python-format
msgid "Failed to modify quota settings for user %s on partition %s"
msgstr ""
"Konnte Quota-Einstellungen für den Benutzer %s auf der Partition %s nicht "
"modifizieren"

#: umc/python/quota/tools.py:183
msgid "Generating the quota information file failed"
msgstr "Erstellung der Quota-Informationsdatei ist fehlgeschlagen"

#: umc/python/quota/tools.py:167
msgid "Mounting the partition has failed"
msgstr "Einhängen der Partition ist fehlgeschlagen"

#: umc/python/quota/partition.py:105
msgid "No partition found"
msgstr "Keine Partition gefunden"

#: umc/python/quota/user.py:74
#, python-format
msgid "No partition found (%s)"
msgstr "Keine Partition gefunden (%s)"

#: umc/python/quota/tools.py:173 umc/python/quota/tools.py:189
msgid "Operation was successful"
msgstr "Operation war erfolgreich"

#: umc/python/quota/partition.py:120
msgid "Quota support successfully activated"
msgstr "Quota-Unterstützung erfolgreich aktiviert"

#: umc/python/quota/partition.py:136
msgid "Quota support successfully deactivated"
msgstr "Quota-Unterstützung erfolgreich deaktiviert"

#: umc/python/quota/tools.py:178
msgid "Remounting the partition has failed"
msgstr "Erneutes Einhängen der Partition ist fehlgeschlagen"

#: umc/python/quota/tools.py:170 umc/python/quota/tools.py:186
msgid "Restarting the quota services has failed"
msgstr "Neustart des Quota-Dienstes ist fehlgeschlagen"

#: umc/python/quota/user.py:173
msgid "Successfully removed quota settings"
msgstr "Quota-Einstellungen erfolgreich entfernt"

#: umc/python/quota/user.py:143
msgid "Successfully set quota settings"
msgstr "Quota-Einstellungen erfolgreich gesetzt"

#: umc/python/quota/user.py:70
#, python-format
msgid "The following partition is currently not mounted: %s"
msgstr "Die folgende Partition ist derzeit nicht eingebunden: %s"

#: umc/python/quota/user.py:65
#, python-format
msgid "The following partition is mounted mounted without quota support: %s"
msgstr "Die folgende Partition ist ohne Quota-Unterstützung eingebunden: %s"

#: umc/python/quota/partition.py:102
msgid "This partition is currently not mounted"
msgstr "Die Partition ist derzeit nicht eingebunden"

#: umc/python/quota/tools.py:164
msgid "Unmounting the partition has failed"
msgstr "Aushängen der Partition ist fehlgeschlagen"
